language: python
sudo: required

install:
  - sudo pip install yamllint

matrix:
    include:
        - os: linux
          dist: trusty
script:
  - yamllint -s -c Test/yamllint.conf Packets.yml Types.yml Packets/*.yml
